services:
  - type: web
    name: GlobalPad
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: node deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://pvsprasad814:bunny@cluster0.ukgkdkw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: "3000"
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: true
    numInstances: 1 